name: CI/CD Frontend Pipeline

on:
  push:
    paths:
      - "front/**"
      - ".github/workflows/frontend.yml"
    branches:
      - main
  pull_request:
    paths:
      - "front/**"
      - ".github/workflows/frontend.yml"
    branches:
      - main

jobs:
  test-frontend:
    name: Run Tests & Coverage (Front-end)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install Dependencies & Run Tests
        run: |
          cd front
          npm install
          npm run test -- --browsers=ChromeHeadless --no-watch --no-progress --code-coverage

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: angular-coverage
          path: front/coverage/

  sonar-frontend:
    name: SonarQube Analysis (Front-end)
    needs: test-frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectBaseDir: front
          args: >
            -Dsonar.projectKey=white-wolf-web_BobApp-Front
            -Dsonar.organization=white-wolf-web
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=src/app
            -Dsonar.tests=src/app
            -Dsonar.test.inclusions=**/*.spec.ts
            -Dsonar.javascript.lcov.reportPaths=coverage/bobapp/lcov.info
            -Dsonar.exclusions=node_modules/**,dist/**,.vscode/**,.github/**,src/environments/**

  build-and-push-frontend:
    name: Build & Push Docker Image (Front-end)
    needs: sonar-frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Frontend Image
        run: |
          cd front
          docker build -t stephanegamot/bobapp-front .
          docker push stephanegamot/bobapp-front
